### ISSUE TITLE
code availability

### ISSUE THREAD

**Issue by tteofili** [shallinan1/MarcoDetoxification#1]
Hello @shallinan1, will the code be made available ?

**Comment by shallinan1** [comment]
Thanks for the comment! We will work to make this available within the next couple days.

**Comment by tteofili** [comment]
in case that might be useful, I'm working on reproducing / extending your work, see https://github.com/trustyai-explainability/trustyai-explainability/issues/289

**Comment by ShawMask** [comment]
+1

**Comment by shallinan1** [comment]
Thank you for opening the issue! I have finished uploading the code, models, datasets, and documentation to the repository. Please feel free to open an additional issue if something is not working correctly.

In addition @tteofili, thank you so much for your interest in reproducing and extending our work - I will check that out soon! Please feel free to reach out with any additional questions/ideas here or to my email at hallisky@uw.edu.
